# Generated by Django 2.0.6 on 2018-06-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'private'), (2, 'public')], default=2),
        ),
        migrations.AddField(
            model_name='measurement',
            name='expiration',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='units',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
