# Generated by Django 2.0.6 on 2018-06-06 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimentor', '0004_auto_20180606_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='experimentor.Experiment'),
        ),
    ]
