# Generated by Django 2.0.6 on 2018-06-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentor', '0006_experiment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='slug',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
