# Generated by Django 2.0.6 on 2018-06-07 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimentor', '0007_signal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'running'), (2, 'stopped'), (3, 'finished'), (4, 'paused')], default=2, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='experimentor.Signal'),
        ),
    ]
